# -*- coding: utf-8 -*-
"""Music_DS_A1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-SYHGGnLuypieVeeJt-6PF_ghtKELDW9
"""

# Importing Necessary Modules!

import numpy as np
from scipy.io.wavfile import write
import sounddevice as sd

# Defining parameters for the Sine Wave

frequency = 440  # Hz
duration = 1  # seconds
sample_rate = 44100  # samples per second
amplitude = 8192  # Quarter of maximum 16-bit amplitude

# Generating the sine wave

t = np.linspace(0, duration, int(duration * sample_rate), endpoint=False)
sine_wave = amplitude * np.sin(2 * np.pi * frequency * t)

# Generating the clipped sine wave

clipped_wave = np.clip(2 * sine_wave, -amplitude, amplitude)

# Writing the sine wave to the same directory

write("sine.wav", sample_rate, sine_wave.astype(np.int16))

# Writing the clipped sine wave to the same directory

write("clipped.wav", sample_rate, clipped_wave.astype(np.int16))

# Playing the audio

sd.play(clipped_wave.astype(np.float32), sample_rate)
sd.wait()  # Wait for playback to finish